// 为一个全局对象
//
console.log(process === global.process);
// console.log(process);

console.log(process.argv);

// -- stdin / stdout 标准输入输出流 IO
// 标准输入设备
// 标准输出设备
//
// like console.log
process.stdout.write("dfsdfsdfsdf");
// read

// 默认输入流是关闭，要监听需要开启输入流
//
process.stdin.resume();
// 监听数据输入
process.stdin.on("data", chunk => {
  console.log("输入了: " + chunk);
});

/****
process {
  version: 'v12.3.1',
  versions: {
    node: '12.3.1',
    v8: '7.4.288.27-node.18',
    uv: '1.29.1',
    zlib: '1.2.11',
    brotli: '1.0.7',
    ares: '1.15.0',
    modules: '72',
    nghttp2: '1.38.0',
    napi: '4',
    llhttp: '1.1.3',
    http_parser: '2.8.0',
    openssl: '1.1.1b',
    cldr: '35.1',
    icu: '64.2',
    tz: '2019a',
    unicode: '12.1'
  },
  arch: 'x64', // cpu 架构
  platform: 'linux',
  release: {
    name: 'node',
    sourceUrl: 'https://nodejs.org/download/release/v12.3.1/node-v12.3.1.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v12.3.1/node-v12.3.1-headers.tar.gz'
  },
  _rawDebug: [Function: _rawDebug],
  moduleLoadList: [
    'Internal Binding native_module',
    'Internal Binding errors',
    'Internal Binding buffer',
    'NativeModule internal/errors',
    'Internal Binding config',
    'Internal Binding constants',
    'Internal Binding util',
    'Internal Binding types',
    'NativeModule internal/util',
    'NativeModule internal/util/types',
    'NativeModule internal/assert',
    'NativeModule internal/util/inspect',
    'NativeModule events',
    'NativeModule internal/validators',
    'NativeModule internal/buffer',
    'Internal Binding icu',
    'NativeModule buffer',
    'NativeModule internal/process/per_thread',
    'NativeModule internal/process/main_thread_only',
    'Internal Binding process_methods',
    'Internal Binding credentials',
    'NativeModule internal/process/stdio',
    'Internal Binding async_wrap',
    'Internal Binding task_queue',
    'NativeModule internal/async_hooks',
    'NativeModule internal/process/promises',
    'NativeModule internal/fixed_queue',
    'NativeModule internal/process/task_queues',
    'Internal Binding trace_events',
    'NativeModule internal/console/constructor',
    'NativeModule internal/console/global',
    'NativeModule internal/util/inspector',
    'Internal Binding inspector',
    'NativeModule internal/querystring',
    'NativeModule internal/constants',
    'NativeModule path',
    'Internal Binding url',
    'NativeModule internal/url',
    'NativeModule internal/encoding',
    'Internal Binding timers',
    'NativeModule internal/linkedlist',
    'NativeModule internal/priority_queue',
    'NativeModule internal/util/debuglog',
    'NativeModule internal/timers',
    'NativeModule timers',
    'NativeModule internal/process/execution',
    'NativeModule internal/process/warning',
    'Internal Binding options',
    'NativeModule internal/options',
    'NativeModule internal/bootstrap/pre_execution',
    'NativeModule internal/inspector_async_hook',
    'Internal Binding contextify',
    'NativeModule util',
    'NativeModule vm',
    'Internal Binding fs',
    'NativeModule internal/fs/utils',
    'NativeModule fs',
    'NativeModule internal/idna',
    'NativeModule url',
    'NativeModule internal/modules/cjs/helpers',
    'NativeModule internal/modules/cjs/loader',
    'Internal Binding module_wrap',
    'NativeModule internal/streams/pipeline',
    'NativeModule internal/streams/end-of-stream',
    'NativeModule internal/streams/legacy',
    'NativeModule internal/streams/buffer_list',
    'NativeModule internal/streams/destroy',
    'NativeModule internal/streams/state',
    'NativeModule _stream_readable',
    'NativeModule _stream_writable',
    'NativeModule _stream_duplex',
    'NativeModule _stream_transform',
    'NativeModule _stream_passthrough',
    'NativeModule stream',
    'NativeModule internal/fs/sync_write_stream'
  ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events: [Object: null prototype] {
    warning: [Function: onWarning],
    newListener: [Function: startListeningIfSignal],
    removeListener: [Function: stopListeningIfSignal]
  },
  _eventsCount: 3,
  _maxListeners: undefined,
  domain: null,
  _exiting: false,
  config: {
    target_defaults: {
      cflags: [],
      default_configuration: 'Release',
      defines: [],
      include_dirs: [],
      libraries: []
    },
    variables: {
      asan: 0,
      build_v8_with_gn: false,
      coverage: false,
      debug_nghttp2: false,
      enable_lto: false,
      enable_pgo_generate: false,
      enable_pgo_use: false,
      force_dynamic_crt: 0,
      gas_version: '2.27',
      host_arch: 'x64',
      icu_data_in: '../../deps/icu-small/source/data/in/icudt64l.dat',
      icu_endianness: 'l',
      icu_gyp_path: 'tools/icu/icu-generic.gyp',
      icu_locales: 'en,root',
      icu_path: 'deps/icu-small',
      icu_small: true,
      icu_ver_major: '64',
      llvm_version: 0,
      node_byteorder: 'little',
      node_code_cache_path: 'yes',
      node_debug_lib: false,
      node_enable_d8: false,
      node_enable_v8_vtunejit: false,
      node_install_npm: true,
      node_module_version: 72,
      node_no_browser_globals: false,
      node_prefix: '/',
      node_release_urlbase: 'https://nodejs.org/download/release/',
      node_report: true,
      node_shared: false,
      node_shared_cares: false,
      node_shared_http_parser: false,
      node_shared_libuv: false,
      node_shared_nghttp2: false,
      node_shared_openssl: false,
      node_shared_zlib: false,
      node_tag: '',
      node_target_type: 'executable',
      node_use_bundled_v8: true,
      node_use_dtrace: false,
      node_use_etw: false,
      node_use_large_pages: false,
      node_use_node_snapshot: false,
      node_use_openssl: true,
      node_use_v8_platform: true,
      node_with_ltcg: false,
      node_without_node_options: false,
      openssl_fips: '',
      openssl_is_fips: false,
      shlib_suffix: 'so.72',
      target_arch: 'x64',
      v8_enable_gdbjit: 0,
      v8_enable_i18n_support: 1,
      v8_enable_inspector: 1,
      v8_no_strict_aliasing: 1,
      v8_optimized_debug: 1,
      v8_promise_internal_field_count: 1,
      v8_random_seed: 0,
      v8_trace_maps: 0,
      v8_use_siphash: 1,
      v8_use_snapshot: 1,
      want_separate_host_toolset: 0
    }
  },
  abort: [Function: abort],
  umask: [Function: umask],
  chdir: [Function: chdir], //改变进程工作目录
  cwd: [Function: cwd], // 进程工作目录
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  reallyExit: [Function: reallyExit],
  _kill: [Function: _kill],
  hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
  cpuUsage: [Function: cpuUsage],
  memoryUsage: [Function: memoryUsage], // node 内存使用情况 unit byte
  kill: [Function: kill], // 杀
  exit: [Function: exit], //退出
  getuid: [Function: getuid],
  geteuid: [Function: geteuid],
  getgid: [Function: getgid],
  getegid: [Function: getegid],
  getgroups: [Function: getgroups],
  initgroups: [Function: initgroups],
  setgroups: [Function: setgroups],
  setegid: [Function],
  seteuid: [Function],
  setgid: [Function],
  setuid: [Function],

  // ---- IO ----
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  // ---- IO ----

  openStdin: [Function],
  allowedNodeEnvironmentFlags: [Getter/Setter],
  assert: [Function: deprecated],
  features: {
    inspector: true,
    debug: false,
    uv: true,
    ipv6: true,
    tls_alpn: true,
    tls_sni: true,
    tls_ocsp: true,
    tls: true,
    cached_builtins: true
  },
  _fatalException: [Function],
  setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
  hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
  emitWarning: [Function: emitWarning],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: runNextTicks],
  env: { //环境变量
    ALACRITTY_LOG: '/tmp/Alacritty-5578.log',
    BROWSER: '/usr/bin/chromium',
    COLORTERM: 'truecolor',
    DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus',
    DESKTOP_SESSION: 'i3',
    DESKTOP_STARTUP_ID: 'i3/~|.i3|shell.sh/590-2-aizigao-pc_TIME505102',
    DISPLAY: ':0',
    EDITOR: '/usr/bin/nvim',
    ELM_SCALE: '1.5',
    GDK_DPI_SCALE: '0.5',
    GDK_SCALE: '2',
    GDMSESSION: 'i3',
    GTAGSLABEL: 'pygments',
    GTK2_RC_FILES: '/home/aizigao/.gtkrc-2.0',
    GTK_IM_MODULE: 'fcitx',
    GTK_MODULES: 'canberra-gtk-module',
    HOME: '/home/aizigao',
    I3SOCK: '/run/user/1000/i3/ipc-socket.590',
    LANG: 'en_US.UTF-8',
    LC_ADDRESS: 'zh_CN.UTF-8',
    LC_CTYPE: 'en_US.UTF-8',
    LC_IDENTIFICATION: 'zh_CN.UTF-8',
    LC_MEASUREMENT: 'zh_CN.UTF-8',
    LC_MONETARY: 'zh_CN.UTF-8',
    LC_NAME: 'zh_CN.UTF-8',
    LC_NUMERIC: 'zh_CN.UTF-8',
    LC_PAPER: 'zh_CN.UTF-8',
    LC_TELEPHONE: 'zh_CN.UTF-8',
    LC_TIME: 'zh_CN.UTF-8',
    LESS: '-R',
    LOGNAME: 'aizigao',
    LSCOLORS: 'Gxfxcxdxbxegedabagacad',
    LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
    MAIL: '/var/spool/mail/aizigao',
    MOZ_PLUGIN_PATH: '/usr/lib/mozilla/plugins',
    NVM_DIR: '/home/aizigao/.nvm',
    NVM_LAZY_LOAD: 'true',
    OLDPWD: '/home/aizigao/MyWorkPlace/keepTraining/node_basic',
    PAGER: 'less',
    PATH: '/home/aizigao/.nvm/versions/node/v12.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/aizigao/.cache/vim/dein/repos/github.com/junegunn/fzf/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl',
    PLASMA_USE_QT_SCALING: '1',
    PWD: '/home/aizigao/MyWorkPlace/keepTraining/node_basic',
    QT_AUTO_SCREEN_SCALE_FACTOR: '0',
    QT_IM_MODULE: 'fcitx',
    QT_QPA_PLATFORMTHEME: 'qt5ct',
    QT_SCREEN_SCALE_FACTORS: '2',
    SHELL: '/usr/bin/zsh',
    SHLVL: '3',
    TERM: 'screen-256color',
    TMUX: '/tmp//tmux-1000/default,10881,0',
    TMUX_PANE: '%14',
    TMUX_PLUGIN_MANAGER_PATH: '/home/aizigao/.tmux/plugins/',
    USER: 'aizigao',
    WINDOWID: '58720261',
    XAUTHORITY: '/home/aizigao/.Xauthority',
    XDG_CURRENT_DESKTOP: 'i3',
    XDG_GREETER_DATA_DIR: '/var/lib/lightdm-data/aizigao',
    XDG_RUNTIME_DIR: '/run/user/1000',
    XDG_SEAT: 'seat0',
    XDG_SEAT_PATH: '/org/freedesktop/DisplayManager/Seat0',
    XDG_SESSION_CLASS: 'user',
    XDG_SESSION_DESKTOP: 'i3',
    XDG_SESSION_ID: 'c2',
    XDG_SESSION_PATH: '/org/freedesktop/DisplayManager/Session0',
    XDG_SESSION_TYPE: 'x11',
    XDG_VTNR: '7',
    XMODIFIERS: '@im=fcitx',
    ZSH: '/home/aizigao/.oh-my-zsh',
    _: '/home/aizigao/.nvm/versions/node/v12.3.1/bin/node',
    ALL_PROXY: 'socks5://127.0.0.1:1080',
    NVM_CD_FLAGS: '-q',
    NVM_BIN: '/home/aizigao/.nvm/versions/node/v12.3.1/bin',
    VIMRUNTIME: '/usr/share/nvim/runtime',
    NVIM_LISTEN_ADDRESS: '/tmp/nvimjIGUbL/0',
    VIM: '/usr/share/nvim',
    MYVIMRC: '/home/aizigao/.config/nvim/init.vim',
    VIM_PATH: '/home/aizigao/.config/nvim',
    DATA_PATH: '/home/aizigao/.cache/vim',
    VIMCONFIG: '/home/aizigao/.config/nvim'
  },
  title: 'node', // 当前进程名
  argv: [
    '/home/aizigao/.nvm/versions/node/v12.3.1/bin/node',
    '/home/aizigao/MyWorkPlace/keepTraining/node_basic/process.js'
  ],
  execArgv: [],
  pid: 22987,
  ppid: 22169,
  execPath: '/home/aizigao/.nvm/versions/node/v12.3.1/bin/node', // 运行
  debugPort: 9229,
  argv0: 'node',      // -- 命令行参数数组
  _preload_modules: [],
  mainModule: Module {
    id: '.',
    path: '/home/aizigao/MyWorkPlace/keepTraining/node_basic',
    exports: {},
    parent: null,
    filename: '/home/aizigao/MyWorkPlace/keepTraining/node_basic/process.js',
    loaded: false,
    children: [],
    paths: [
      '/home/aizigao/MyWorkPlace/keepTraining/node_basic/node_modules',
      '/home/aizigao/MyWorkPlace/keepTraining/node_modules',
      '/home/aizigao/MyWorkPlace/node_modules',
      '/home/aizigao/node_modules',
      '/home/node_modules',
      '/node_modules'
    ]
  }
}

**********/
